# Nusmart Platform Support
EXTRA_CFLAGS += -Iarch/arm/mach-ns115/include/
#snd-soc-nusmart-plat-objs := nusmart-plat.o

obj-$(CONFIG_SND_NUSMART_SOC_EVA_I2S) += dma.o
obj-$(CONFIG_SND_NUSMART_SOC_EVA_I2S) += nusmart-eva-i2s-dai.o

# Nusmart Machine Support
obj-$(CONFIG_SND_SOC_ALC5631) += nusmart-mach-rt5631.o
obj-$(CONFIG_SND_SOC_ALC5616) += nusmart-mach-rt5616.o
obj-$(CONFIG_SND_SOC_ES8388) += nusmart-mach-es8388.o
